// Tokens are generated by the lexer
export class Token {
  constructor(swatchNumber, swatchColor) {
    Object.assign(this, { swatchNumber, swatchColor });
  }
}

export class Program {
  constructor(statements) {
    this.statements = statements;
  }
}

export class Assignment {
  constructor(target, source) {
    Object.assign(this, { target, source });
  }
}

export class Call {
  constructor(callee, args, isStatement = false) {
    Object.assign(this, { callee, args, isStatement });
  }
}

export class BinaryExpression {
  constructor(op, left, right) {
    Object.assign(this, { op, left, right });
  }
}

export class UnaryExpression {
  constructor(op, operand) {
    Object.assign(this, { op, operand });
  }
}
